language: node_js
node_js:
  - 12

install:
  - yarn global add @cloudflare/wrangler
  - yarn
cache: yarn

env:
  - PACKAGE_VERSION="1.0.*"
script:
  - CF_ACCOUNT_ID=c562df9070bcec00181f4f8f80cefafd CF_API_TOKEN=8bdAdBP52lxMZr9Us5nvAVuqoxFlwFS5n_FQUHWt wrangler publish
